# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productdevelopment', '0003_auto_20171124_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='style',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='productdevelopment.Customer'),
            preserve_default=False,
        ),
    ]
