# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productdevelopment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finished_Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_finished', models.DateTimeField()),
                ('bundle', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='productdevelopment.Bundle')),
                ('operation', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='productdevelopment.Operations')),
            ],
        ),
        migrations.CreateModel(
            name='Production_Line',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=500)),
                ('line_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Production_Line_Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='productdevelopment.Deliverable')),
                ('operations', models.ManyToManyField(
                    blank=True, to='productdevelopment.Operations')),
                ('production_line', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='production.Production_Line')),
            ],
        ),
        migrations.CreateModel(
            name='Production_Line_Worker',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('production_line', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='production.Production_Line')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=500)),
                ('worker_details', models.CharField(max_length=500)),
                ('worker_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='production_line_worker',
            name='worker',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='production.Worker'),
        ),
        migrations.AddField(
            model_name='finished_bundle',
            name='production_line_worker',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='production.Worker'),
        ),
    ]
