# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20171124_1342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker_Landline_Number',
            new_name='Worker_Contact_Number',
        ),
        migrations.RemoveField(
            model_name='worker_mobile_number',
            name='worker',
        ),
        migrations.DeleteModel(
            name='Worker_Mobile_Number',
        ),
    ]
