# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('description', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=100)),
                ('measurements', models.CharField(max_length=500)),
                ('order_specifications', models.CharField(max_length=100)),
                ('stock', models.DecimalField(decimal_places=10, max_digits=19)),
                ('part_type', models.CharField(choices=[
                 ('fabric', 'fabric'), ('accessory', 'accessory')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Part_In',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=19)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Part_Out',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=19)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateField()),
                ('terms_of_payment', models.CharField(max_length=100)),
                ('prepared_by', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('po_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order_Item',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('uom', models.CharField(max_length=20)),
                ('date_due', models.DateField()),
                ('unit_price', models.IntegerField()),
                ('purchase_order', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='materialplanning.Purchase_Order')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='supplier',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='materialplanning.Supplier'),
        ),
    ]
