# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productdevelopment', '0001_initial'),
        ('materialplanning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part_out',
            name='deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productdevelopment.Deliverable'),
        ),
        migrations.AddField(
            model_name='part_out',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materialplanning.Part'),
        ),
        migrations.AddField(
            model_name='part_in',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materialplanning.Part'),
        ),
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materialplanning.Supplier'),
        ),
    ]
