# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialplanning', '0002_auto_20171101_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_material_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Raw_Material_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=19)),
                ('date_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Raw_Material_Exit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=19)),
                ('date_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Contact_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Landline_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landline_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Mobile_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='part',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='part_in',
            name='part',
        ),
        migrations.RemoveField(
            model_name='part_out',
            name='deliverable',
        ),
        migrations.RemoveField(
            model_name='part_out',
            name='part',
        ),
        migrations.RemoveField(
            model_name='purchase_order',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchase_order_item',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
    ]
